# Generated by Django 3.0.6 on 2020-05-29 00:18

from django.db import migrations, models
import django.db.models.deletion
import gas.person.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('DTS', models.DateTimeField(verbose_name='Дата начала работы')),
                ('DTE', models.DateTimeField(verbose_name='Дата окончания работы')),
            ],
            options={
                'verbose_name': 'Дата время работы',
                'verbose_name_plural': 'График работы',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='native_lang',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=gas.person.models.Person.save_to_path, verbose_name='Файл документа'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('worked', 'Работает'), ('fired', 'Уволен'), ('candidate', 'Кандидат'), ('refused', 'Отклонен'), ('approved', 'Проверен'), ('reserve', 'В резерве')], max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='worktime',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worktimes', to='person.Person'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worktimes', to='person.Station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='person',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='person.Station', verbose_name='Станция'),
        ),
    ]
