# Generated by Django 3.0.5 on 2020-04-27 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsche'), ('fi', 'Suomi')], default='ru', max_length=2, verbose_name='Язык интерфейса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DTC', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('DTU', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('native_lang', models.CharField(max_length=50, verbose_name='Родной язык')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
